### ISSUE TITLE
[Feature Request]: Why so many releases? Adjust CI settings?

### ISSUE THREAD

**Issue by BlueDrink9** [puremourning/vimspector#100]
This project has 66 releases. Every merge, `mergify` adds a release. Your workflow involves a lot of merges. The changelogs are commits lists, and usually most of the changes are duplicated, making it hard to see what is different between releases.

The best way to easily follow the progress of a github project is by watching the releases, but with vimspector it's too easy to get lost in the flood. Could I request, if possible, that you update `mergify` or whatever other tool is used, so that releases are only done when **you** think the project is ready for a new release?

I'm possibly making an issue out of something very small here, but I thought I may as well ask.

**Comment by puremourning** [comment]
Every commit to master is a release. The release process is "push to green" if you like.

I don't maintain versions or anything like that. The GitHub release mechanism is purely to make installation easier (i.e. by downloading a prefab tarball, rather than cloning and running `./install_gadget.py`).

The change log is `git log`

**Comment by puremourning** [comment]
P.S. For things like this, i would prefer to discuss in Gitter; the issue [tracker is for bugs and feature requests](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md)
