### ISSUE TITLE
Use [VimspectorEval] to check variable but the debug output buffer does not automatically scroll to the bottom line

### ISSUE THREAD

**Issue by NGPONG** [puremourning/vimspector#187]
## Environment 
- ubuntu 20.04
- neovim  v 0.4.3
- c debug program

Hey there, thanks for providing such a powerful plugin.
I like to use the command **VimspectorEval** to output the status of the variable, but in use, I found that each time the **VimspectorEval** command is executed, three sentences are output, which are respectively:
- Evaluating:
- Evaluated:
- **result: (That the value i need)**

For these three sections of output, the last one is actually what I really need, but please forget about it. That's not the point I'm making. The most important thing is that the cursor will not be positioned on the last line after every output of these three sentences, and the status will be as follows

![微信截图_20200611221507](https://user-images.githubusercontent.com/38415769/84396940-14c43780-ac31-11ea-9cbf-e64392f80523.png)

Then, I have to manually scroll to the last line again to get the information I really need, which is the return value of the **result**

![微信图片_20200611222117](https://user-images.githubusercontent.com/38415769/84398007-f4e14380-ac31-11ea-8109-91beda6027c9.png)

I tried to improve this experience with the following vimscript, but it didn't seem to work
ps: I'm a vim novice, not familiar with vim scripts, thanks for lot!
```vim
function! s:PrintVariable(_val)
  execute 'VimspectorEval '. a:_val
  call feedkeys("G") " jump the last line
endfunction
command! -nargs=1 Check call s:PrintVariable(<f-args>)
```
BTW, I don't think **Evaluating** and **Evaluated** result will seem to matter to most people (from my point), maybe removing it will improve the experience of using this plugin.

**Comment by puremourning** [comment]
Please can you complete the full issue template?

I get what you're saying, and i appreciate the clear and precise explanation, but all the other debugging info is useful and avoids me having to say, for example "Are you using neovim?"

**Comment by puremourning** [comment]
Sorry deleted my last comment 'cos you clearly say you're using neovim!

Anyway, thanks for the clear and precise issue report. In future I'd appreciate it if you fill in the issue template as requested in CONTRIBUTING.md.

Anyway to your point I seem to recall there is some reason why it is this way, and that reason is neovim-specific. Could you please try using Vim ?

FWIW, i find that the Watch window is _much_ better for this sort of thing `VimspectorWatch <expression>` will show in the watch window and update on every step. You can likely also see `argc` in the locals window.

There's also #52 which might supersede this.
