### ISSUE TITLE
[Feature Request]: Support NodeJS 12

### ISSUE THREAD

**Issue by perfectspr** [puremourning/vimspector#217]
[vscode-node-debug2](https://github.com/microsoft/vscode-node-debug2) has supported node>=8.0. 
Can Vimspector also support the same versions?

**Comment by puremourning** [comment]
The problem was that npm install fails With later nodes. Iirc the adapter works With any node after running that. 

If there’s another way to install it that works I would gladly accept a PR to make it work. 

I almost never node so it’s not a high priority for me. 

What do you mean by sample versions?

**Comment by perfectspr** [comment]
I see,  I will try to solve this issue.

**Comment by puremourning** [comment]
Just tried with vscode-node-debug2 version 'v1.42.5' and node latest. looks like it works.

should just be a 1 line change in gadgets.py and remove some lines in installer.py's InstallNodeDebug
