### ISSUE TITLE
[Feature Request]: Java Hot Code Replacement support

### ISSUE THREAD

**Issue by Frederick888** [puremourning/vimspector#252]
**Is your feature request related to a problem? Please describe.**
I'm using Vimspector with coc.nvim, [coc-java](https://github.com/neoclide/coc-java) and [coc-java-debug](https://github.com/dansomething/coc-java-debug).

Right now if I change my code during debug, the code gets compiled automatically and then I can see `Unhandled event: hotcodereplace`. It'd be nice if Vimspector can handle this event and send the new class files to JVM.

**Describe the solution you'd like**
HCR support, so that hot replacement happens wherever possible during debug.

**Describe alternatives you've considered**
DCEVM + Auto HotSwap. But this is usually very resource intensive as the JVM needs to watch all the class files. I'm looking at ~5x CPU usage with auto HotSwap. If I configure some [`extraClassPath`s](http://hotswapagent.org/mydoc_configuration.html) the CPU usage can further sky rockets to 20x.

**Comment by puremourning** [comment]
> https://github.com/dansomething/coc-java-debug/issues/9#issuecomment-686855635

Sorry it's not feasible for me to support custom DAP protocol additions. I'm just one person in my spare time. This custom exetnsion to the protocol is not documented at all (I looked at the code to find that it even exists).

If DAP is updated to support 'hot code replace' in a fully documented and supported way then I would consider it, but while it remains a complexly custom server-specific event, that's a rabbit hole I don't have the capacity to enter.

I'm loath to open up any kind of API for custom even handling in Vimsepctor because custom events are a scourge on a standard protocol and just create work for client authors rather than enhancing the protocol centrally and sensibly.

**Comment by Frederick888** [comment]
Cool, that's totally understandable. Thanks for your time and effort in developing and maintaining this project and hope some JVM developer can document this functionality better.

**Comment by puremourning** [comment]
Thanks for understanding.

**Comment by puremourning** [comment]
If anyone just wants this to "work" by magic, add this to `python3/vimspector/debug_session.py` after the `OnEvent_stopped` definition:

```python
  def OnEvent_hotcodereplace( self, message ):
    # Hack for java debug server hot-code-replace
    self._connection.DoRequest( None, {
      'command': 'redefineClasses',
      'arguments': {},
    } )
 
```

**Comment by Frederick888** [comment]
@puremourning Wow, terrific! Thank you! May I know if this is gonna be merged down the line?

**Comment by puremourning** [comment]
Possibly. No promises.

**Comment by puremourning** [comment]
Ref https://github.com/microsoft/debug-adapter-protocol/issues/176

**Comment by puremourning** [comment]
Ref https://github.com/microsoft/debugpy/issues/212#issuecomment-765903809
