### ISSUE TITLE
[Feature Request]: Add support for cursor hover for variable evaluation

### ISSUE THREAD

**Issue by dsych** [puremourning/vimspector#309]
**Is your feature request related to a problem? Please describe.**
Consider switching away from `balloonexpr` for variable evaluation. I saw this in your backlog and wanted to get some extra info. Are you still thinking about supporting mouse hover or should it be at cursor hover? 

**Describe the solution you'd like**
i have been messing around with nvim's floating windows and got it working by adding a new function that could be called to evaluate expression under cursor. This is similar to what [coc-nvim](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-show-documentation-of-symbol-under-cursor-also-known-as-cursor-hover) is doing for hover.
This can also be easily implemented on the vim side by using `popup_atcursor`. However, this will mean that mouse hover will no longer work...

**Describe alternatives you've considered**
We could always implement both cursor hover and mouse hover(for vim only), but somehow it does not sit well with me, given that neovim has no intention of implementing `balloonexpr`

**Additional context**
See [my commit](https://github.com/dsych/vimspector/commit/eee3e4fb08a27b7bedf211e3f149692451c65803). You can just invoke `vimspector#internal#state#Tooltip` once debugging is activated.
![Peek 2020-11-29 23-03](https://user-images.githubusercontent.com/16144679/100567812-6cb23180-3297-11eb-81d6-2fd164fed75b.gif)

**Comment by puremourning** [comment]
yeah, I would like to replace balloons with something more general and/or powerful. the main problem with them (and popups too) is that there's no good way to represent that many expression results "break down" and can be expanded etc. This works well in the watches and locals window, but in the popup there's just the current value. This is one of the main reasons that I haven't worked too hard on this so far.

I have been thinking that a better functionality would be to have a mapping that adds the `word` under the cursor as a watch in the watch window, but that can already be done trivially.

Balloons are great because they are very simple. For vim with mouse support, my plan was to use something like :help popup_beval() to emulate the balloon function using a popup.

I don't want vimspector features to be restricted by the capabilities of any one of the 2 Vims. What I was thinking about for nevim was the virtual text feature as an alternative, rather than popup.

Would be happy to discuss ideas and review a PR, but I don't think I'm likely to get to this myself any time soon, as I personally mostly just use the watch window. I have found that to be more wholesome/complete in the general case. Particularly if you have the prompt buffer version (vim or neovim master).

**Comment by dsych** [comment]
I see your point. However, I dont see inability to expand entries inside a popup as a limitation, rather a clear indication of what this feature is for.
In my experience, hover functionality is rarely used for drilling down to see all members of a given type. That is what the watch and variables windows are for. I see hover functionality as more of a quick check for a simple enough type e.g. int, string etc. For something more complex, you are correct, one should use the variables window...

Alternatively, we could implement expand functionality in the popup window similarly to how coc.nvim does it for completion list. Something like having `<c-p>` and `<c-n>` defined for moving the highlight line around and `<cr>` for toggling a fold.

**Comment by puremourning** [comment]
Fixed by #350
