### ISSUE TITLE
[Feature Request]: Persistent breakpoints

### ISSUE THREAD

**Issue by sheerun** [puremourning/vimspector#453]
**Is your feature request related to a problem? Please describe.**
I'm unsable to set breakpoints without starting debugger, breakpoints aren't persistent

**Describe the solution you'd like**
I'm able to toggle breakpoints before debugger is started. These breakpoints are automatically sent to debugger when it is launched. Breakpoints can be persisted in session data.

**Comment by puremourning** [comment]
There's a trello card for this https://trello.com/c/vdD6LPsj

The main blocker is just _where_ to persist them. There are a number of options, but there's no _obvious_ winner that works for everyone. I also don't want to settle on a persistence model if there might be other things we might want to persist in the future. I think this is a legit request, so shall we re-open?

**Comment by puremourning** [comment]
Maybe we could add :VimspectorMkSession with an optional file name argument 🤔

**Comment by puremourning** [comment]
How about this sort of thing:
if a .vimspector.json file exists, that is the "project root"
otherwise CWD is project root
if a file named .vimspector.session exists in project root, automatically updcate it with breakpoints and saved answers on start/end of a debug session (?)
otherwise, ONCE ask the user when starting a new session if they would like to create a session file in project root
add VimspectorMkSession / VimspectorLoadSession and a setting to disable auto-save for advanced uses
i.e. we don't create a file that the user didn't ask for, but if it's there, we will do everythong automatically


from discussion: https://gitter.im/vimspector/Lobby?at=613e72a199b7d9752807ac5e
