### ISSUE TITLE
Go support via Delve

### ISSUE THREAD

**Issue by myitcv** [puremourning/vimspector#48]
_If you will excuse me not completing the template, this is a rather more vague request for information_

In a tools session at  GopherCon 2019 ([notes](https://docs.google.com/document/d/1-RVyttQ0ncjCpR_sRwizf-Ubedkr0Emwmk2LhnsUOmE/edit#heading=h.4a2ftcuzucfc)) there was an interesting discussion started about Delve and the Debugger Adapter Protocol. Delve has become the de facto debugger for Go, and it looks like it will be blessed as the official debugger by the Go team. 

As part of trying to understand how Delve can become better integrated in various editors, the Debugger Adapter Protocol was brought up. Delve does not currently speak this protocol, but if there is sufficient support the work could be done (relatively easily). 

I've previously seen this project, but it was this discussion that prompted me to raise an issue:

* what are your thoughts/experience of the Debugger Adapter Protocol?
* do you have any advice on how to proceed on the question of how to integrate Delve with Vim (and other editors)
* ...

The context of considering the Debugger Adapter Protocol is the Go now has an official LSP server, `gopls`. Hence, building on that success, it seems logical to consider the Debugger Adapter Protocol.

Thanks in advance

**Comment by puremourning** [comment]
> what are your thoughts/experience of the Debugger Adapter Protocol?

Im many ways it is just like LSP. Your experience with govim (or is it vim-go ? ;)) will tell you all you need to know about the protocol/transport, etc. 

From a practical perspective, i have found implementing a DAP client generally less frustrating than implementing a LSP client. It seems to have fewer warts in the protocol and _generally_ requires less language/adapter-specific knowledge in the client.

Most interactions are pretty well-defined, and the interactions themselves are fairly simple. It doesn't suffer so badly from feature bloat, churn or poorly defined features (like LSP commands) etc. (probably because it's less well-known).

I have also implemented a DAP server (for TCL) and i found that was simple and intuitive too.

So I guess i would say from that perspective it's all good.

Of course, by distilling the functionality to what can be implemented in every client and work for every language, there are some functional holes. If users are used to REPL-style debugging, there is not a good way to achieve this with DAP (for example). 

> do you have any advice on how to proceed on the question of how to integrate Delve with Vim (and other editors)

I think my advice would be that if you want the debugger to get the most exposure, wrapping a DAP shim around its internals would be a good way to make it available.

For example, making it work with Vimspector should require _zero_ changes to Vimspector. 

However, i would be more than happy to include it as a "fully-supported" server (i.e. we include the basic config and way to install it within Vimspector) as that reduces the user's install/setup burden.

Happy to answer any other questions/etc..

> The context of considering the Debugger Adapter Protocol is the Go now has an official LSP server, gopls

yes indeed. i'd recommend it. DAP and LSP are becoming de facto. They aren't ideal, and the model tends to make things a bit slow, but i guess we're willing to pay that runtime costs for the convenience of just pressing `<F5>` in our favourite editor and debugging our stuff.

Feel free to reach out on Gitter if you want to chat further.

As this isn't really an "issue", i'm going to close it, but the discussion can continue.

**Comment by puremourning** [comment]
Wait re-opening. This issue can track adding in the "first class" support, and any testing that is needed.

**Comment by myitcv** [comment]
Thank you very much indeed. This is an outstanding answer, and exactly the sort of insight I was after. Very much appreciate your insight.

**Comment by puremourning** [comment]
@myitcv looks like there's already a debug adapter written by Microsoft that is wrapping delve: https://github.com/Microsoft/vscode-go 

specifically: https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts

I'll see if it works.

**Comment by puremourning** [comment]
I set it up, but it seems bugged.

```
2019-07-31 17:49:38,190 - WARNING - User Msg: Paused in thread 0 due to breakpoint
2019-07-31 17:49:38,203 - DEBUG - Sending Message: {"command": "threads", "seq": 3, "type": "request"}
2019-07-31 17:49:38,203 - DEBUG - Message received: {'seq': 6, 'type': 'response', 'request_seq': 2, 'command': 'configurationDone', 'success': True}
2019-07-31 17:49:38,215 - DEBUG - Message received: {'seq': 7, 'type': 'response', 'request_seq': 3, 'command': 'threads', 'success': True, 'body': {'threads': []}}
```

It's not legal for there to be no threads, and this means that Vimspector never gets a stack, so never updates the current PC.

I have pushed the build changes to [a branch](https://github.com/puremourning/vimspector/commit/446985ddc72f604ec0eec793a6e9f6e07ae6f8b6) in case you're interested. The [`.vimspector.json`](https://github.com/puremourning/vimspector/commit/446985ddc72f604ec0eec793a6e9f6e07ae6f8b6#diff-796d5733e6816cf4b6b0e85ecd1aa4aa) that's required is very simple.

**Comment by puremourning** [comment]
I repro'd the bug in VSCode too, and will raise on their tracker. 

Basically `stopOnEntry` doesn't work, but if you set some breakpoints manually before launch, it does work, but you have to _manually_ run "Continue" request after launching.

This brings me to something that I didn't say before, but is important: @myitcv just like LSP, don't expect servers to work if you're protocol-compliant, but don't work _exactly_ the same way as vscode. Server authors consider themselves "working" if they work in VSCode, and they don't strictly follow the DAP (it's _much_ worse with LSP, but DAP is the same - as it is with this adapter).

**Comment by puremourning** [comment]
<img width="1013" alt="Screenshot 2019-07-31 at 18 30 23" src="https://user-images.githubusercontent.com/10584846/62233821-4473a380-b3c1-11e9-8051-b7496052c2b6.png">

Proof.
