### ISSUE TITLE
[Feature Request]: Disassembly view

### ISSUE THREAD

**Issue by tim-seoss** [puremourning/vimspector#510]
Firstly, thanks very much to everyone who's worked on vimspector - it's great to be able do debug from the comfort of vim...

I'm writing some code for a constrained environment (Cortex M microcontroller), and it'd be great to be able to view the disassembly for individual lines and functions etc.

The Microsoft Debug Adapter Protocol specification seems to include a Disassemble request
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disassemble

...and CodeLLDB seems to have support for this feature:
https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#disassembly-view

I'm not really sure what the best way to present disassembly to the user would be, some ideas:
- A separate vim window which shows the disassembly synced to the current code view (maybe with source code lines interleaved with assembly, in order to show the mapping as far as possible).  Maybe the current line in the code view would be highlighted in the assembly view, and/or the visual selection in the code view would be highlighed in the assembly view.
- A popup to display the disassembly for the current line, function, block etc.

Any thoughts or ideas welcome!

**Comment by puremourning** [comment]
I'd like this too. My current "plan" is to work out the best way to do [memory display](https://github.com/puremourning/vimspector/issues/498) first, then disassembly next.

The reason of that is that the UI for a good disassembly view is really hard and will require a _lot_ of work.

The simplest-possible-thing(TM) is to just display what the DAP server returns in a new buffer with no relation to the actual code. This would be very similar to the implementation that I'm playing with for [memory dump](https://github.com/puremourning/vimspector/pull/507), but would have limited real use cases. 

Interleaving the code lines and the assembly would be tricky (basically impossible in vim currently without making an essentially static copy of the buffer). But it might be possible as a snapshot mechanism. Then you have syntax highlighting and stuff like that which will be its own challenge.

So yeah, in summary, this would be a cool feature but I am unlikely to have the kind of time required to develop it any time soon.

**Comment by puremourning** [comment]
I had a think about this, and outlined an approach that might work. It's still a ton of work though, unfortunately.

- add disassembly option to the stack trace window winbar. this might not seem completely intuitive, but in DAP the disassembly is actually of a stack frame or memory reference. annoyingly, this requires supplying an "instruction count". I suppose the idea for this is for the UI to work out this value, but ugh...
- add a command to the variables/watches windows to show the disassembly for the referenced memory (less useful, but I guess this could work for function pointers?)
- open a new window showing a scratch buffer holding the disassembly. split the code window (:split) for this. In both wide and narrow modes, this is _probably_ the only practical choice. TODO: we could add _yet more_ logic to try and work out if we can fit another code-window sized window vertically, but ick.. it's so fiddly.
- add a "PC" sign/line highlight to that based on the info in the disassembly response and the selected stack frame: The `memoryReference` required for the disassembly is found in the `instructionPointerReference` member of the `StackFrame`.
- add instruction stepping to a winbar in that window. this just does the normal step, but with instruction as the type. it seems intuitive for "normal step" to be "step instruction" when the disassembly view is current.

The main problem I see is that we have to statically decide how many instructions to request. It would be nice if adapters could default this and return the disassembly of the _function_ in the stack trace. Given that's the only place you can really get a reference. But alas, I think that requires some annoying faffing, like:

- work out the actual number of lines in the disassembly window, and request 2x that
- hook a cursor moved event in that buffer which (debounced) requires a refresh based on the current cursor position. try to maintain a window around the cursor so there's always a screenful below. we can consider using the offset param to maintain only 1 screenful above too.

it's _possible_ but again, lots of typing for what is ultimately not a very useful function. It would be _better_ if we could just request the full output for the function in one go, statically. even if that's slow, it's a one-off operation rather than constantly making many small requests, which is guaranteed to be slow! 

I might be missing something in the spec, but I don't see any obvious way to do simply. Maybe debuggers just don't know, but that seems absolutely unlikely on the basis that there's an optional `endLine` member on a `stackFrame` meaning the end line of the method.

**Comment by puremourning** [comment]
> ...and CodeLLDB seems to have support for this feature:
https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#disassembly-view

Sadly not. This is a custom codelldb thing and not actually the DAP disasseble request.

**Comment by puremourning** [comment]
But would you believe it, I done implemented it in CodeLLDB for fun and, well, it kinda works and I'm kinda shocked:

<img width="1372" alt="Screenshot 2022-01-24 at 22 35 53" src="https://user-images.githubusercontent.com/10584846/150876547-e0a104ac-ef23-48b2-aa38-901d4a25f03f.png">

**Comment by puremourning** [comment]
This was implemented by #681
