### ISSUE TITLE
[Feature Request]: Add .vim to the config search path

### ISSUE THREAD

**Issue by m-lima** [puremourning/vimspector#514]
**Is your feature request related to a problem? Please describe.**
Vim configuration files are often stored in a `.vim` directory, e.g. `.vim/coc-setting.json` overrides project-specific CoC settings. This makes it easier to add to `.gitignore` IDE configuration directories like `.idea`, `.vscode`, `.vim`, etc.

Currently, vimspector searches up the path tree for root `.vimspector.json` and doesn't consider the `.vim` directory. Since vimspector is vim-specific, it would make sense and be cleaner to make it aware of this directory.

**Describe the solution you'd like**
When walking up the tree path, consider not only the `.vimspector.json`, but also `.vim/.vimspector.json` files.

**Describe alternatives you've considered**
Other alternative would be to make the file locations configurable.

**Comment by puremourning** [comment]
seems related https://github.com/puremourning/vimspector/issues/495 and https://github.com/puremourning/vimspector/issues/380

I don't think that `$PROJECT_ROOT/.vim` is particularly canonical or de factor. I haven't see a precedent for that (other than you mention  coc, which meh) - are there other examples?  I initially found it confusing because I read `.vim` to mean `~/.vim` and though immediately that the solution was to use `g:vimspector_base_dir`.

It just doesn't seem that hard to add `.vimspector.*` to your `.gitignore`.
