### ISSUE TITLE
[Feature Request]: Don't open a new terminal window after every restart

### ISSUE THREAD

**Issue by doronbehar** [puremourning/vimspector#54]
I'm sorry for the issues bombard, I was just thinking that these are different topics to discuss so I didn't want to put them all in one big issue.

So today, after some debug sessions with vimspector, I noticed that the stdout/stderr window of my running program is being recreated every time I start a debug session. I must say that it's kind of annoying to quit the old window every time a new session is started. I'm also a Neovim refugee because of #30 and so I'm not used yet to Vim's `:terminal`s which makes this process a little bit harder for me TBH..

**Comment by puremourning** [comment]
The server says ‘run this command in a terminal’. I can’t know that you don’t want to keep the old one for some reason. 

I mean there are probably options to improve this I admit (I find it a bit annoying too - particularly when each new terminal is half the width. 

Suggestions welcome.

**Comment by puremourning** [comment]
I suppose re-using any existing window for the terminal would be a legit behaviour at least if that terminal job was in a finished state.

**Comment by doronbehar** [comment]
Do you think it would be possible to append to the same terminal the output of the next run and perhaps use some kind of a distinguishing separator such as:

```
____________________________________

```

So it'll be easier to distinguish between the current and the previous execution? Maybe we can just use a normal buffer and not a `:terminal` buffer?

**Comment by puremourning** [comment]
Maybe possible. Would have to check the vim docs. We just run a job with output set to a buffer. Not 100% sure if you can re use buffer for that but it seems likely.

**Comment by puremourning** [comment]
Reference https://github.com/puremourning/vimspector/blob/master/python3/vimspector/code.py#L180

**Comment by puremourning** [comment]
I just tried something which re-uses the terminal window. There's no way to "append" to the buffer because it's not rally a buffer when it's a terminal window.

The problem I guess is that we can't know that's always correct. The server could send _any number_ of [runInTerminal](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal) requests. 

Perhaps we could only re-use the terminal if the job within it is complete. I think that would probably work well enough for most use cases. Otherwise we may need to add another WinBar to the terminal window and emulate "tabs" (like the logs/output window)

**Comment by doronbehar** [comment]
Wow, I've just checked out the latest version and it works excellently. Thanks @puremourning ! This is so much better right now!

**Comment by puremourning** [comment]
Great to hear !
