### ISSUE TITLE
Interactive debugging prompt auto-closing enclosing characters ([, (, {) before cursor

### ISSUE THREAD

**Issue by zbs** [puremourning/vimspector#734]
### Description

In the interactive prompt in a Python debugging session, parentheses, brackets, quotes, and curly braces are sporadically auto-closing behind the cursor, instead of around it. It causes situations like this:
```
df.groupby([]""
```
as I'm trying to write
```
df.groupby(["columnA", "columnB"])
```

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Open nvmi
2. Open Python module
3. Call `:VimspectorLaunch`
4. Upon hitting breakpoint, switch to interactive console
5. Try typing something that has [, {, ", or (.

### Expected Behaviour

Expect the auto-closing behavior to disabled, or at least for enclosing characters to surround the cursor, not go before it.

### Actual Behaviour

Enclosing characters are auto-closed before the cursor

### Additional information

My connection is quite slow, so perhaps the lag figures into the behavior.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

HEAD

### Vim version

```Text
NVIM v0.5.0
```

### Operating System

RHEL 8.3

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
So you said:

> Works with clean config?

> Yes

And

> Sample project works?

> Not reproducable with sample project


Which suggests the problem is your environment, or other plug-ins. 

There is nothing in vimspector that attempts to complete perentheses. However I do know that debugpy includes them in its completion suggestions. However I can't reproduce your issue in vim. 

Please can you list precise steps to reproduce using the _minimal vimcr_ and the _sample projects_ as requested in CONTRIBUTING.md so that I can understand?

If this amounts to interference from another plug-in then at least include which one and why you think it's vimspector bug rather than other-plug-in bug.
